import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

register(StyleDictionary);

// CSS vars는 kebab-case 관례 사용 (tokens-studio 기본은 camelCase)
StyleDictionary.registerTransformGroup({
  name: 'tokens-studio/css',
  transforms: [
    'ts/descriptionToComment',
    'ts/size/px',
    'ts/opacity',
    'ts/size/lineheight',
    'ts/typography/fontWeight',
    'ts/resolveMath',
    'ts/size/css/letterspacing',
    'ts/color/css/hexrgba',
    'ts/color/modifiers',
    'name/kebab',
  ],
});

function setDeep(obj, path, value) {
  let cur = obj;
  for (let i = 0; i < path.length - 1; i++) {
    if (!cur[path[i]]) cur[path[i]] = {};
    cur = cur[path[i]];
  }
  cur[path[path.length - 1]] = value;
}

StyleDictionary.registerFormat({
  name: 'javascript/tailwind-preset',
  format({ dictionary }) {
    const colors = {};
    const fontSize = {};
    const fontWeight = {};
    const fontFamily = {};
    const lineHeight = {};

    for (const token of dictionary.allTokens) {
      const [category, ...rest] = token.path;
      const key = rest.join('-');

      if (category === 'color') setDeep(colors, rest, token.value);
      else if (category === 'font-size') fontSize[key] = token.value;
      else if (category === 'font-weight') fontWeight[key] = token.value;
      else if (category === 'font-family') fontFamily[key] = token.value;
      else if (category === 'line-height') lineHeight[key] = token.value;
    }

    const preset = {
      theme: {
        extend: { colors, fontSize, fontWeight, fontFamily, lineHeight },
      },
    };

    return (
      '/** Auto-generated by Style Dictionary — do not edit */\n' +
      `module.exports = ${JSON.stringify(preset, null, 2)};\n`
    );
  },
});

const sd = new StyleDictionary({
  source: ['tokens/tokens.json'],
  preprocessors: ['tokens-studio'],
  platforms: {
    css: {
      transformGroup: 'tokens-studio/css',
      buildPath: 'dist/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: { selector: ':root', outputReferences: false },
        },
      ],
    },
    tailwind: {
      transformGroup: 'tokens-studio',
      buildPath: 'dist/tailwind/',
      files: [
        {
          destination: 'preset.cjs',
          format: 'javascript/tailwind-preset',
        },
      ],
    },
    js: {
      transformGroup: 'tokens-studio',
      buildPath: 'dist/js/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
