name: Auto Main PR

on:
  push:
    branches:
      - develop

concurrency:
  group: develop-to-main-pr
  cancel-in-progress: true

jobs:
  create-or-update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changelog
        id: changelog
        run: |
          git fetch origin main
          LOGS=$(git log origin/main..HEAD --oneline --pretty=format:"- %s")
          echo "logs<<EOF" >> $GITHUB_OUTPUT
          echo "$LOGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or Update Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "main"
          pr_title: "[배포 대기] main 최신화"
          pr_body: |
            ## 작업 요약
            Develop 브랜치의 최신 변경 사항을 Main 브랜치로 반영합니다.

            ### 최근 머지된 내역
            ${{ steps.changelog.outputs.logs }}
          pr_label: "main"
          github_token: ${{ secrets.YML_GITHUB_TOKEN }}
